# Generated by Django 2.0.5 on 2018-06-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dosen', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DosenGelar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ijazah', models.IntegerField(blank=True, null=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='DosenMatakuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pengajaran', models.IntegerField(blank=True, null=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='DosenSkor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor_pendidikan', models.IntegerField(blank=True, null=True)),
                ('skor_pengajaran', models.IntegerField(blank=True, null=True)),
                ('skor_penelitian', models.IntegerField(blank=True, null=True)),
                ('totalskor', models.IntegerField(blank=True, null=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen')),
            ],
        ),
        migrations.CreateModel(
            name='Gelar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gelar', models.CharField(blank=True, max_length=11, null=True)),
                ('jenjang', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JabatanFungsional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatanfungsional', models.CharField(blank=True, max_length=100, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keahlian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_keahlian', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matakuliah', models.CharField(blank=True, max_length=100, null=True)),
                ('keahlian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.Keahlian')),
            ],
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_penelitian', models.CharField(blank=True, max_length=200, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('dosen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen')),
                ('keahlian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.Keahlian')),
            ],
        ),
        migrations.CreateModel(
            name='PerguruanTinggi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perguruantinggi', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='penelitian',
            name='perguruantinggi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.PerguruanTinggi'),
        ),
        migrations.AddField(
            model_name='dosenskor',
            name='keahlian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Keahlian'),
        ),
        migrations.AddField(
            model_name='dosenmatakuliah',
            name='matakuliah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.MataKuliah'),
        ),
        migrations.AddField(
            model_name='dosenmatakuliah',
            name='perguruantinggi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.PerguruanTinggi'),
        ),
        migrations.AddField(
            model_name='dosengelar',
            name='gelar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Gelar'),
        ),
        migrations.AddField(
            model_name='dosengelar',
            name='perguruantinggi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.PerguruanTinggi'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='jabatanfungsional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.JabatanFungsional'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='perguruantinggi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.PerguruanTinggi'),
        ),
    ]
