# Generated by Django 2.0.5 on 2018-06-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0002_dosen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelar',
            name='nama_gelar',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
