# Generated by Django 2.0.6 on 2018-06-30 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0003_auto_20180627_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosenskor',
            name='totalskor',
        ),
    ]
