# Generated by Django 2.0.6 on 2018-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0004_remove_dosenskor_totalskor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_pendidikan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_penelitian',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_pengajaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
