# Generated by Django 2.0.6 on 2018-07-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0005_auto_20180630_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_programstudi', models.CharField(blank=True, max_length=100, null=True)),
                ('keahlian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.Keahlian')),
            ],
        ),
        migrations.AddField(
            model_name='dosen',
            name='programstudi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.ProgramStudi'),
        ),
    ]
