# Generated by Django 2.0.6 on 2018-07-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0006_auto_20180705_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenjang', models.CharField(max_length=255)),
                ('rank', models.IntegerField(unique=True)),
                ('skor_jenjang', models.DecimalField(decimal_places=2, max_digits=12, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jabatanfungsional',
            name='skor_jabatan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gelar',
            name='jenjang',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gelar',
            name='jenjang_ref',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Jenjang'),
            preserve_default=False,
        ),
    ]
