# Generated by Django 2.0.6 on 2018-07-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0007_auto_20180705_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gelar',
            name='jenjang_ref',
        ),
        migrations.AlterField(
            model_name='gelar',
            name='jenjang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Jenjang'),
        ),
    ]
