# Generated by Django 2.0.6 on 2018-07-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0008_auto_20180705_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jabatanfungsional',
            old_name='skor_jabatan',
            new_name='skor_jabatanfungsional',
        ),
    ]
