# Generated by Django 2.0.6 on 2018-07-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0009_auto_20180705_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
        ),
        migrations.AlterField(
            model_name='gelar',
            name='jenjang',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='Jenjang',
        ),
    ]
