# Generated by Django 2.0.6 on 2018-07-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0010_auto_20180705_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenjang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jenjang', models.CharField(max_length=255)),
                ('rank', models.IntegerField(default=0, unique=True)),
                ('skor_jenjang', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='dosen',
            name='perguruantinggi',
        ),
    ]
