# Generated by Django 2.0.6 on 2018-07-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0011_auto_20180705_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='perguruantinggi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.PerguruanTinggi'),
        ),
        migrations.AddField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
