# Generated by Django 2.0.6 on 2018-07-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0012_auto_20180705_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programstudi',
            name='keahlian',
        ),
    ]
