# Generated by Django 2.0.6 on 2018-07-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0013_remove_programstudi_keahlian'),
    ]

    operations = [
        migrations.AddField(
            model_name='programstudi',
            name='keahlian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.Keahlian'),
        ),
    ]
