# Generated by Django 2.0.6 on 2018-07-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0014_programstudi_keahlian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
