# Generated by Django 2.0.6 on 2018-07-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0016_auto_20180705_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelar',
            name='jenjang',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Jenjang'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jenjang',
            name='skor_jenjang',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
