# Generated by Django 2.0.6 on 2018-07-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0017_auto_20180705_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenjang',
            name='rank',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
