# Generated by Django 2.0.5 on 2018-07-05 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0018_auto_20180705_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStudiKeahlian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keahlian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.Keahlian')),
            ],
        ),
        migrations.RemoveField(
            model_name='programstudi',
            name='keahlian',
        ),
        migrations.AddField(
            model_name='programstudikeahlian',
            name='programstudi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.ProgramStudi'),
        ),
    ]
