# Generated by Django 2.0.6 on 2018-07-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0019_auto_20180705_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_pendidikan',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_penelitian',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_pengajaran',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='jenjang',
            name='skor_jenjang',
            field=models.FloatField(null=True),
        ),
    ]
