# Generated by Django 2.0.6 on 2018-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0020_auto_20180706_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_pendidikan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_penelitian',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dosenskor',
            name='skor_pengajaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='jenjang',
            name='skor_jenjang',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
