# Generated by Django 2.0.6 on 2018-07-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0022_auto_20180706_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalvar',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
