# Generated by Django 2.0.6 on 2018-07-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0023_auto_20180706_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosenskor',
            name='skor_jabatan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dosenskor',
            name='z_skor_jabatan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dosenskor',
            name='z_skor_pendidikan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dosenskor',
            name='z_skor_penelitian',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dosenskor',
            name='z_skor_pengajaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
