# Generated by Django 2.0.6 on 2018-07-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0025_auto_20180706_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='total_jumlah_penelitian',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dosen',
            name='total_jumlah_pengajaran',
            field=models.IntegerField(default=0),
        ),
    ]
