# Generated by Django 2.0.6 on 2018-07-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0026_auto_20180706_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosenJumlahPenelitian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_penelitian', models.IntegerField(default=0)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen')),
                ('keahlian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Keahlian')),
            ],
        ),
        migrations.CreateModel(
            name='DosenJumlahPengajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_pengajaran', models.IntegerField(default=0)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen')),
                ('keahlian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Keahlian')),
            ],
        ),
    ]
