# Generated by Django 2.0.5 on 2018-07-07 06:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0027_dosenjumlahpenelitian_dosenjumlahpengajaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
