# Generated by Django 2.0.5 on 2018-07-07 06:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0029_auto_20180707_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenjang',
            name='skor_jenjang',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
