# Generated by Django 2.0.5 on 2018-09-03 02:09

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0030_auto_20180707_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosenJumlahProyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_proyek', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_proyek', models.CharField(blank=True, max_length=200, null=True)),
                ('tahun', models.IntegerField(blank=True, null=True)),
                ('pengguna_jasa', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dosen',
            name='total_jumlah_proyek',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jabatanfungsional',
            name='skor_jabatanfungsional',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='proyek',
            name='dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen'),
        ),
        migrations.AddField(
            model_name='proyek',
            name='keahlian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caripakar_app.Keahlian'),
        ),
        migrations.AddField(
            model_name='dosenjumlahproyek',
            name='dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Dosen'),
        ),
        migrations.AddField(
            model_name='dosenjumlahproyek',
            name='keahlian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caripakar_app.Keahlian'),
        ),
    ]
