# Generated by Django 2.0.5 on 2018-09-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caripakar_app', '0031_auto_20180903_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosenskor',
            name='skor_proyek',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dosenskor',
            name='z_skor_proyek',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
    ]
